# Generated by Django 4.0.4 on 2022-06-01 19:27

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=150)),
                ('number', models.IntegerField()),
                ('complement', models.CharField(max_length=150)),
                ('postal_code', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(code=400, message='The postal_code number must follow the format: xxxxx-xxx', regex='^[0-9]{5}(?:-[0-9]{3})?$')])),
            ],
        ),
    ]
