# Generated by Django 4.0.4 on 2022-05-25 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(code=400, message='The postal_code number must follow the format: xxxxx-xxx', regex='^[0-9]{5}(?:-[0-9]{3})?$')]),
        ),
    ]
