# Generated by Django 4.0.4 on 2022-05-24 03:05

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code=400, message='The phone number must follow the format: (xx) 9xxxx-xxxx', regex='^\\([1-9]{2}\\) 9[1-9][0-9]{3}-[0-9]{4}$')])),
            ],
        ),
    ]
