# Generated by Django 4.0.4 on 2022-05-24 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_documents', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='personal_documents',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='personal_documents.personal_document'),
        ),
    ]
