# Generated by Django 4.0.4 on 2022-05-25 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_alter_address_postal_code'),
        ('employees', '0003_employee_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='employees', to='addresses.address'),
        ),
    ]
