# Generated by Django 4.0.4 on 2022-05-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='personal_code',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
