# Generated by Django 4.0.4 on 2022-05-29 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_personal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='personal_code',
            field=models.IntegerField(unique=True),
        ),
    ]
