# Generated by Django 4.0.4 on 2022-05-30 05:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employee_personal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='personal_code',
            field=models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator(code=400, message='The personal code is six numbers, format: xxxxxx', regex='^[0-9]{6}')]),
        ),
    ]
