# Generated by Django 4.0.4 on 2022-05-29 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employee_personal_code'),
        ('work_days', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workDays', to='employees.employee'),
        ),
    ]
