# Generated by Django 4.0.4 on 2022-05-29 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employee_personal_code'),
        ('work_days', '0002_workday_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workday',
            name='employee',
        ),
        migrations.AddField(
            model_name='workday',
            name='employee_code',
            field=models.ForeignKey(db_column='employee_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employees.employee', to_field='personal_code'),
        ),
    ]
