# Generated by Django 4.0.4 on 2022-05-30 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_days', '0003_remove_workday_employee_workday_employee_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='workday',
            name='checkin',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='workday',
            name='checkout',
            field=models.TimeField(null=True),
        ),
    ]
