# Generated by Django 4.0.4 on 2022-05-30 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_days', '0004_workday_date_alter_workday_checkin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workday',
            name='is_holiday',
        ),
    ]
