# Generated by Django 4.0.4 on 2022-06-01 20:24

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_type', models.CharField(max_length=20)),
                ('contract_duration', models.DateField()),
                ('salary', models.DecimalField(decimal_places=3, max_digits=6)),
                ('position', models.CharField(max_length=150)),
                ('work_shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='shifts.shift')),
            ],
        ),
    ]
