# Generated by Django 4.0.4 on 2022-05-24 20:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_type', models.CharField(max_length=20)),
                ('contract_duration', models.DateField()),
                ('salary', models.FloatField()),
                ('position', models.CharField(max_length=150)),
                ('work_shift', models.CharField(max_length=20)),
            ],
        ),
    ]
