# Generated by Django 4.0.4 on 2022-05-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='salary',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
