# Generated by Django 4.0.4 on 2022-05-26 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
        ('contracts', '0003_alter_contract_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='work_shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='shifts.shift'),
        ),
    ]
