# Generated by Django 4.0.4 on 2022-05-26 17:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('base_checkin', models.TimeField()),
                ('base_checkout', models.TimeField()),
            ],
        ),
    ]
