# Generated by Django 4.0.4 on 2022-05-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_default_shifts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
