# Generated by Django 4.0.4 on 2022-05-24 18:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=15)),
                ('nit', models.CharField(max_length=15)),
                ('rg', models.CharField(max_length=15)),
                ('ctps', models.CharField(max_length=15)),
                ('cnpj', models.CharField(max_length=15, null=True)),
            ],
        ),
    ]
