# Generated by Django 4.0.4 on 2022-05-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_document',
            name='cnpj',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='personal_document',
            name='cpf',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='personal_document',
            name='ctps',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='personal_document',
            name='nit',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='personal_document',
            name='rg',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
