# Generated by Django 4.0.4 on 2022-05-27 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_documents', '0002_alter_personal_document_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_document',
            name='cnpj',
            field=models.CharField(max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(code=400, message='The cnpj must follow the format: xx.xxx.xxx/xxxx-xx', regex='[0-9]{2}[\\.][0-9]{3}[\\.][0-9]{3}[\\/][0-9]{4}[-][0-9]{2}$')]),
        ),
        migrations.AlterField(
            model_name='personal_document',
            name='cpf',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(code=400, message='The cpf must follow the format: xxx.xxx.xxx-xx', regex='[0-9]{3}[\\.][0-9]{3}[\\.][0-9]{3}[-][0-9]{2}$')]),
        ),
        migrations.AlterField(
            model_name='personal_document',
            name='ctps',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(code=400, message='The cpts must follow the format: xxxxxxx-xxxx', regex='[0-9]{7}[-][0-9]{4}$')]),
        ),
        migrations.AlterField(
            model_name='personal_document',
            name='nit',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(code=400, message='The nit must follow the format: xxx.xxxxx.xx-x', regex='[0-9]{3}[\\.][0-9]{5}[\\.][0-9]{2}[-][0-9]{1}$')]),
        ),
        migrations.AlterField(
            model_name='personal_document',
            name='rg',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(code=400, message='The rg must follow the format: xx.xxx.xxx-x', regex='[0-9]{2}[\\.][0-9]{3}[\\.][0-9]{3}[-][0-9]{1}$')]),
        ),
    ]
